### ISSUE TITLE
Feature: Static filter control

### ISSUE THREAD

**Issue by EvanBoyle** [EvanBoyle/AzSearch.js#10]
Sometimes users want filtering without faceting. A good example would be the language facet for the [channel9 demo](http://azsearchstore.azurewebsites.net/channel9.html)

![langfacet](https://cloud.githubusercontent.com/assets/2553171/25389412/65bec86c-2985-11e7-84a5-dbf05e198aa4.png)

Rather than searching over multiple languages, the user wants to specify a single language to limit results to (and also always limit other facets to as well). This might make sense as a drop down similar to @m-gagne 's implementation of the orderby control. Depending on the behavior of this control, it might require changes in the search store to introduce a new facet type. We may need to modify the way clearAllFacets behaves as well. This control could probably take in a list of options, but we could probably try to list the options automatically based on the result of a facet query. Static options would probably be fine to start. This may just end up being a different way of rendering a checkbox facet with slightly different clearAll behavior.

**Comment by m-gagne** [comment]
I think this would be a solid control to have, primarily because as you said there are many times where they want just a single option like in the real-estate I can see where a dropdown would be helpful for say property type (house vs apartment) instead of a checkbox list. 

The idea of having dynamic population is interesting, essentially running a * search and caching the facets on load... this could help solve some other UX issues as well as allow for better "first page load" experience, but I think that should be separated as another issue/enhancement. The store could be updated with a cached set of initial results for UI population.
