### ISSUE TITLE
Range filter visible without search

### ISSUE THREAD

**Issue by m-gagne** [EvanBoyle/AzSearch.js#6]
The range filter (sqft) is visible at page load even when no search has been performed. 

## Expected:
* No facet controls are rendered

## Actual:
* Range Facet is rendered

## Repo

* Load `realestatedemo.html`
* Range Facet Control is visible

**Comment by m-gagne** [comment]
@EvanBoyle, currently the RangeFacet can't tell if a query has been performed or not, would it make sense to add props that supply the actual results min/max values? which could be used to determine if a search has been applied and what the actual min/max is? I noticed in the RangeFacet type there is `upperBucketCount` and `lowerBucketCount` but they always seem to be zero, was that their intended purpose?

**Comment by EvanBoyle** [comment]
@m-gagne The min/max values should be available through the facet prop that is passed in. there is another property passed in called loadedResultsCount. We could probably add a check to see if count ===0 and the filterLower==min and filterUpper===max, then don't display the slider. 

As for upperBuckerCount and lowerBucketCount, those values are supposed to hold the counts for results outside of the filtered range. These are currently always zero due to an idiosyncrasy with the way faceting and filtering compose in Azure Search. Consider the a range slider over field "foo" where min = 0, max = 10. Lets say the filter is set to lower=5, upper=7. This will produce:

 filterClause: "foo ge 5 and foo le 7",
 facetClause: "foo,values:5|7"

Today we issue a single request with both of these. Issuing the facet clause alone would also return counts for values < 5 and values > 7, but since we're filtering to values between 5 and 7 for the search request, those counts come back as 0 since they don't fall within the filter. There is a similar issue with checkbox facets as well. I have some work I'd like to do in the search store to support "advanced" faceting mode. The idea is that we'll issue multiple requests, fully filtered requests for the search results, and then individual requests for the facets to maintain counts even when filters are applied.

**Comment by m-gagne** [comment]
Upon further testing there doesn't appear to be a way to hide this control (other than on the very first page load where store.results.count === -1.  Because if you filter using say "this will not return anything" the result count is 0. So I have a PR that will solve for the "cold load" scenario but that's all.
